# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-02 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone_Number',
            new_name='PhoneNumber',
        ),
        migrations.RenameModel(
            old_name='Sign_Name',
            new_name='SignName',
        ),
    ]
